demo-app added
Ganji-NaveenKumar/External-ReactDemo pull request #2
Opened 2024-07-19 17:55 UTC by Ganji-NaveenKumar

External React Demo
demo-app(react-app) added Demo-app

2024-07-19 18:38 UTC, saicharan-zemoso requested changes
please provide a new screenshot of the component after resolving all the comments.

2024-07-19 18:38 UTC, saicharan-zemoso commented on Demo-app/demo-app/public/assets/Component.png
check the font and download the font if not available.

2024-07-19 18:38 UTC, saicharan-zemoso commented on Demo-app/demo-app/public/assets/Ethereum.svg
place the images under public/assets/icons or images

2024-07-19 18:38 UTC, saicharan-zemoso commented on Demo-app/demo-app/src/components/molecules/IconTypography/index.tsx
> +const StyledDiv = styled.div`
don't use div

2024-07-19 18:38 UTC, saicharan-zemoso commented on Demo-app/demo-app/src/components/molecules/ItemCard/index.tsx
> +const IconTypoStyle = styled.div`
use mui component

2024-07-19 18:38 UTC, saicharan-zemoso commented on Demo-app/demo-app/src/components/molecules/IconTypography/index.tsx
> +  typographyBody: string;
rename the props use better property names

2024-07-19 18:38 UTC, saicharan-zemoso commented on Demo-app/demo-app/src/components/molecules/ItemCard/index.tsx
> +                Body={item.Percentage}
same here

2024-07-21 14:56 UTC, Ganji-NaveenKumar commented
![image](https://github.com/user-attachments/assets/228be52d-443b-421e-8ba9-1d50cdf9019d)

2024-07-23 07:55 UTC, saicharan-zemoso approved these changes
looks good to me

2024-07-23 08:02 UTC, merged